sudo: required
services:
  - docker
language: python
python: "3.5"
matrix:
  include:
    env: TOX_ENV=py36
    python: "3.6"
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=lint
  - TOX_ENV=isort
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
